syntax on
filetype indent plugin on

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set rnu
set title

au FileType python setlocal tabstop=4 expandtab shiftwidth=4 softtabstop=4
au FileType html setlocal spell spelllang=en_au
au FileType mail setlocal spell spelllang=en_au
au FileType tex setlocal spell spelllang=en_au
au BufRead *.txt setlocal spell spelllang=en_au
